import Notes.Papers.CW.ApproxIBP
import Notes.Papers.CW.ArithmeticSpinGlass
import Notes.Papers.CW.ArithmeticSpinGlassAutoChecks
import Notes.Papers.CW.AutoFormalizer
import Notes.Papers.CW.GIBP
import Notes.Papers.CW.LindebergBlockwise
import Notes.Papers.CW.LindebergStep
import Notes.Papers.CW.Lindenberg
import Notes.Papers.CW.RandomPhaseModelMoments
import Notes.Papers.CW.RandomPhaseMoments
import Notes.Papers.CW.TateShafarevich
import Notes.Papers.CW.TateShafarevichAutoChecks
import Notes.Papers.CW.ZetaSpinGlass
import Notes.Papers.CW.ZetaSpinGlassDefs
import Notes.Papers.Kapustin.Krein.AdjointPair
import Notes.Papers.Kapustin.Krein.Basic
import Notes.Papers.Kapustin.Krein.FundamentalDecomposition
import Notes.Papers.Kapustin.Krein.HardyMellinModel
import Notes.Papers.Kapustin.Krein.Intertwining
import Notes.Papers.Kapustin.Krein.KapustinEigenvalue
import Notes.Papers.Kapustin.Krein.KapustinEquiv
import Notes.Papers.Kapustin.Krein.KapustinInverse
import Notes.Papers.Kapustin.Krein.KapustinOperator
import Notes.Papers.Kapustin.Krein.KapustinResolvent
import Notes.Papers.Kapustin.Krein.KapustinTransport
import Notes.Papers.Kapustin.Krein.KreinSelfAdjointSpectral
import Notes.Papers.Kapustin.Krein.RankOne
import Notes.Papers.Kapustin.Krein.RankOneEigenvalue
import Notes.Papers.Kapustin.Krein.RankOneEquiv
import Notes.Papers.Kapustin.Krein.RankOneInverse
import Notes.Papers.Kapustin.Krein.RankOneResolvent
import Notes.Papers.Kapustin.Krein.WeightedL2
import Notes.Papers.Kapustin.Krein.WeightedL2Kapustin
import Notes.Papers.Kapustin.Krein.WeightedL2KapustinEigenvalue
import Notes.Papers.Kapustin.Krein.WeightedL2KapustinEigenvalueShift
import Notes.Papers.Kapustin.Krein.WeightedL2KapustinEquiv
import Notes.Papers.Kapustin.Krein.WeightedL2KapustinInverse
import Notes.Papers.Kapustin.Krein.WeightedL2KapustinNonrealEigenvalue
import Notes.Papers.Kapustin.Krein.WeightedL2KapustinScalarIntegral
import Notes.Papers.Kapustin.Krein.WeightedL2MulEquiv
import Notes.Papers.Kapustin.Krein.WeightedL2MulOpAlgebra
import Notes.Papers.Kapustin.Krein.WeightedL2NonrealShift
