import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Measure.Haar.OfBasis
import Mathlib.Order.CompletePartialOrder

/-!
# Carleson Measures: Core Definitions

This file provides the core definitions for Carleson measure theory.

## Main Definitions

* `CarlesonFamily`: Geometric data for Carleson conditions
* `CarlesonFamily.tent`: The tent (Carleson box) over an indexed base set
* `carlesonNorm`: The Carleson norm (supremum of ratios)
* `IsCarlesonMeasure`: Class for Carleson measures
* `ballFamily`: The standard Carleson family using closed balls

## Tags

Carleson measure, tent, Hardy space
-/

open MeasureTheory Filter Set NNReal ENNReal Metric
open scoped ENNReal NNReal Topology

namespace MeasureTheory

namespace CarlesonMeasure

universe u v

variable {γ : Type u} {ι : Type v}

section Basic

variable [MeasurableSpace γ]

/-- A `CarlesonFamily` on a space `γ` encodes the geometric data needed to define Carleson
measures. -/
structure CarlesonFamily (γ : Type u) [MeasurableSpace γ] where
  /-- The index type for the family of base sets. -/
  ι : Type v
  /-- Maps an index to its base set in `γ`. -/
  baseSet : ι → Set γ
  /-- Maps an index to its characteristic scale. -/
  scale : ι → ℝ≥0
  /-- All base sets are measurable. -/
  measurableSet_baseSet : ∀ i, MeasurableSet (baseSet i)

attribute [simp] CarlesonFamily.measurableSet_baseSet

/-- The **tent** (or **Carleson box**) over an indexed base set. -/
def CarlesonFamily.tent (F : CarlesonFamily γ) (i : F.ι) : Set (γ × ℝ≥0) :=
  F.baseSet i ×ˢ Ioo 0 (F.scale i)

@[simp]
theorem CarlesonFamily.mem_tent_iff (F : CarlesonFamily γ) (i : F.ι) (p : γ × ℝ≥0) :
    p ∈ F.tent i ↔ p.1 ∈ F.baseSet i ∧ p.2 ∈ Ioo 0 (F.scale i) :=
  Set.mem_prod

theorem CarlesonFamily.tent_eq_prod (F : CarlesonFamily γ) (i : F.ι) :
    F.tent i = F.baseSet i ×ˢ Ioo 0 (F.scale i) := rfl

/-- Tents are measurable in the product σ-algebra. -/
theorem CarlesonFamily.measurableSet_tent [TopologicalSpace γ] [BorelSpace γ]
    (F : CarlesonFamily γ) (i : F.ι) :
    MeasurableSet (F.tent i) :=
  (F.measurableSet_baseSet i).prod measurableSet_Ioo

/-- The **Carleson norm** of a measure `μ` on `γ × ℝ≥0` with respect to a boundary measure `ν`
and a Carleson family `F`. -/
noncomputable def carlesonNorm (μ : Measure (γ × ℝ≥0)) (ν : Measure γ)
    (F : CarlesonFamily γ) : ℝ≥0∞ :=
  ⨆ i : F.ι, μ (F.tent i) / ν (F.baseSet i)

@[simp]
theorem carlesonNorm_empty (μ : Measure (γ × ℝ≥0)) (ν : Measure γ) (F : CarlesonFamily γ)
    [IsEmpty F.ι] : carlesonNorm μ ν F = 0 := by
  simp [carlesonNorm]

theorem carlesonNorm_le_iff (μ : Measure (γ × ℝ≥0)) (ν : Measure γ) (F : CarlesonFamily γ)
    (c : ℝ≥0∞) : carlesonNorm μ ν F ≤ c ↔ ∀ i, μ (F.tent i) / ν (F.baseSet i) ≤ c := by
  simp [carlesonNorm, iSup_le_iff]

theorem le_carlesonNorm (μ : Measure (γ × ℝ≥0)) (ν : Measure γ) (F : CarlesonFamily γ)
    (i : F.ι) : μ (F.tent i) / ν (F.baseSet i) ≤ carlesonNorm μ ν F :=
  le_iSup (fun i => μ (F.tent i) / ν (F.baseSet i)) i

/-- Monotonicity of Carleson norm. -/
theorem carlesonNorm_mono {μ₁ μ₂ : Measure (γ × ℝ≥0)} {ν₁ ν₂ : Measure γ}
    (hμ : μ₁ ≤ μ₂) (hν : ν₂ ≤ ν₁) (F : CarlesonFamily γ) :
    carlesonNorm μ₁ ν₁ F ≤ carlesonNorm μ₂ ν₂ F := by
  apply iSup_mono
  intro i
  apply ENNReal.div_le_div
  · exact hμ (F.tent i)
  · exact hν (F.baseSet i)

/-- A measure `μ` on `γ × ℝ≥0` is a **Carleson measure** with respect to a boundary measure `ν`
and a Carleson family `F` if the Carleson norm is finite. -/
class IsCarlesonMeasure [TopologicalSpace γ] [BorelSpace γ]
    (μ : Measure (γ × ℝ≥0)) (ν : Measure γ) (F : CarlesonFamily γ) (K : ℝ≥0) : Prop where
  /-- The measure is locally finite. -/
  isLocallyFinite : IsLocallyFiniteMeasure μ
  /-- The Carleson norm is bounded by K. -/
  carlesonNorm_le : carlesonNorm μ ν F ≤ K

namespace IsCarlesonMeasure

variable [TopologicalSpace γ] [BorelSpace γ]
    {μ : Measure (γ × ℝ≥0)} {ν : Measure γ} {F : CarlesonFamily γ} {K : ℝ≥0}

/-- The Carleson norm of a Carleson measure is finite. -/
theorem carlesonNorm_lt_top (h : IsCarlesonMeasure μ ν F K) : carlesonNorm μ ν F < ⊤ :=
  lt_of_le_of_lt h.carlesonNorm_le ENNReal.coe_lt_top

/-- For any index `i`, the ratio `μ(tent i) / ν(baseSet i)` is bounded by K. -/
theorem tent_measure_div_baseSet_le (h : IsCarlesonMeasure μ ν F K) (i : F.ι) :
    μ (F.tent i) / ν (F.baseSet i) ≤ K :=
  (le_carlesonNorm μ ν F i).trans h.carlesonNorm_le

end IsCarlesonMeasure

end Basic

/-! ## Classical Carleson Measures (Ball Family) -/

section Classical

variable {E : Type*} [MetricSpace E] [MeasurableSpace E] [BorelSpace E]

/-- The **ball family** on a metric space `E`: the Carleson family generated by all closed balls. -/
def ballCarlesonFamily (E : Type*) [MetricSpace E] [MeasurableSpace E] [BorelSpace E] :
    CarlesonFamily E where
  ι := E × ℝ≥0
  baseSet p := closedBall p.1 p.2
  scale p := p.2
  measurableSet_baseSet _ := measurableSet_closedBall

@[simp]
theorem ballCarlesonFamily_baseSet (p : E × ℝ≥0) :
    (ballCarlesonFamily E).baseSet p = closedBall p.1 p.2 := rfl

@[simp]
theorem ballCarlesonFamily_scale (p : E × ℝ≥0) :
    (ballCarlesonFamily E).scale p = p.2 := rfl

/-- The tent over a ball `B(x,r)` in the ball family. -/
theorem ballCarlesonFamily_tent (x : E) (r : ℝ≥0) :
    (ballCarlesonFamily E).tent (x, r) = closedBall x r ×ˢ Ioo 0 r := rfl

end Classical

/-! ## Poisson Extension (Placeholder)

The full Poisson extension API is in `Carleson.lean`. Here we provide
a placeholder for files that need the type signature. -/

section PoissonExtension

/-- Placeholder for the Poisson extension. The full definition using
`RH.RS.PoissonKernelDyadic.Ksigma` is in `Carleson.lean`. -/
noncomputable def poissonExtension (f : ℝ → ℝ) (x : ℝ) (y : ℝ≥0) : ℝ :=
  ∫ t : ℝ, (1 / Real.pi) * ((y : ℝ) / ((x - t)^2 + (y : ℝ)^2)) * f t

end PoissonExtension

end CarlesonMeasure

end MeasureTheory
