name: Lean Build

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install elan
        uses: leanprover/elan-action@v1
        with:
          toolchain: leanprover/lean4:v4.13.0
      - name: Cache Lake
        uses: actions/cache@v4
        with:
          path: |
            ~/.lake
            ./.lake
          key: ${{ runner.os }}-lake-${{ hashFiles('**/lake-manifest.json') }}
      - name: Build RH proof
        run: |
          cd no-zeros
          lake build rh.Proof.Main
      - name: Check no sorries or local axioms
        run: |
          ! grep -R "sorry" -n no-zeros/rh || (echo "found sorry" && exit 1)
          ! grep -R "^axiom " -n no-zeros/rh || (echo "found local axiom" && exit 1)
